service:
  name: wedding-sls

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters #Permite declarar variáveis com informações da AWS

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'} #Se não especificado nenhum stage usar dev como default
  region: sa-east-1
  iamRoleStatements:
    - ${file(iam/GuestTableIAM.yml):GuestTableIAM} #Importa o arquivo e especifíca o objeto GuestTableIAM
resources:
  Resources:
    GuestTable: ${file(resources/GuestTable.yml):GuestTable} #Importa o arquivo o objeto GuestTable
functions:
  guestRegister:
    handler: src/handlers/guestRegister.handler
    events:
      - http:
          method: POST
          path: /guest

custom:
  bundle:
    linting: false #added
