service:
  name: wedding-sls

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters #Permite declarar variáveis com informações da AWS

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'} #Se não especificado nenhum stage usar dev como default
  region: sa-east-1
  environment:
    GUEST_TABLE_NAME: ${self:custom.GuestTable.name}
  iamRoleStatements:
    - ${file(iam/GuestTableIAM.yml):GuestTableIAM} #Importa o arquivo e especifíca o objeto GuestTableIAM

resources:
  Resources:
    GuestTable: ${file(resources/GuestTable.yml):GuestTable} #Importa o arquivo o objeto GuestTable
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

functions:
  guestRegister:
    handler: src/handlers/guestRegister.handler
    events:
      - http:
          method: POST
          path: /guest
          cors: true

  getGuests:
    handler: src/handlers/getGuests.handler
    events:
      - http:
          method: GET
          path: /guests
          cors: true

  getGuest:
    handler: src/handlers/getGuest.handler
    events:
      - http:
          method: GET
          path: /guest/{id}
          cors: true

  updateGuest:
    handler: src/handlers/updateGuest.handler
    events:
      - http:
          method: PATCH
          path: /guest/{id}/update
          cors: true

  deleteGuest:
    handler: src/handlers/deleteGuest.handler
    events:
      - http:
          method: DELETE
          path: /guest/{id}/delete
          cors: true

  notifyGuests:
    handler: src/sweeper/notifyGuests.handler
    events:
      - schedule: rate(1 day)

custom:
  GuestTable: #o nome da tabela assim como o arn serão informados quando houver o deploy
    name: !Ref GuestTable
    arn: !GetAtt GuestTable.Arn
  bundle:
    linting: false #é desaconselhável usar esse parâmetro como false
