service:
  name: wedding-sls

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'} #if this variable is undefined, use dev as default
  region: sa-east-1

resources:
  Resources:
    GuestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GuestTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  guestRegister:
    handler: src/handlers/guestRegister.handler
    events:
      - http:
          method: POST
          path: /guest

custom:
  bundle:
    linting: false #added
