GuestTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: GuestTable-${self:provider.stage} #Adiciona o estágio no nome da tabela
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id #primary key
        KeyType: HASH #unique
